### ISSUE TITLE
Call produce pg-promise exception

### ISSUE THREAD

**Issue by barbaBus** [sipcapture/HEPop#17]
dear Sipcapture Team.
I face this issue when a call is sent to the hom7-hep-influx from heplify.
Here you are the docker output:

heplify-server | SET Bucket ID: hep_proto_1_call
heplify-server | /app/node_modules/pg-promise/lib/formatting.js:154
heplify-server | throw new Error('Property '' + v.name + '' doesn't exist.');
heplify-server | ^
heplify-server |
heplify-server | Error: Property 'sid' doesn't exist.
heplify-server | at query.replace.name (/app/node_modules/pg-promise/lib/formatting.js:154:19)
heplify-server | at String.replace ()
heplify-server | at Object.object (/app/node_modules/pg-promise/lib/formatting.js:134:22)
heplify-server | at $formatQuery (/app/node_modules/pg-promise/lib/formatting.js:295:29)
heplify-server | at format (/app/node_modules/pg-promise/lib/formatting.js:831:16)
heplify-server | at data.map (/app/node_modules/pg-promise/lib/helpers/methods/insert.js:128:26)
heplify-server | at Array.map ()
heplify-server | at Object.insert (/app/node_modules/pg-promise/lib/helpers/methods/insert.js:124:29)
heplify-server | at Object.insert (/app/node_modules/pg-promise/lib/helpers/index.js:52:24)
heplify-server | at Object.exports.insert (/app/src/pgsql.js:101:34)
heplify-server | npm ERR! code ELIFECYCLE
heplify-server | npm ERR! errno 1
heplify-server | npm ERR! hepop@1.0.30 start: node hepop.js -c /app/myconfig.js
heplify-server | npm ERR! Exit status 1
heplify-server | npm ERR!
heplify-server | npm ERR! Failed at the hepop@1.0.30 start script.
heplify-server | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
heplify-server |
heplify-server | npm ERR! A complete log of this run can be found in:
heplify-server | npm ERR! /root/.npm/_logs/2019-10-02T14_26_03_761Z-debug.log

Attached the pcap file of the call sniffed by sngrep on the same server where heplify runs, and the log with the debug option set to true in config.js for HEPop server.

[call-queue.pcap.zip](https://github.com/sipcapture/HEPop/files/3686805/call-queue.pcap.zip)
[call-xcally.log](https://github.com/sipcapture/HEPop/files/3686806/call-xcally.log)

**Comment by lmangani** [comment]
You are using an outdated bundle. Please choose from the following:
https://github.com/sipcapture/homer7-docker/tree/7.7/heplify-server

Feel free to open a new issue if those fail in any way - thanks!

**Comment by lmangani** [comment]
Sorry i close this by mixup. Please explain what you're trying to do and what your scenario involves in as much detail as possible in terms of data sources. What is sending "a call" here? If you're into using SIP, please switch to https://github.com/sipcapture/homer7-docker/tree/7.7/heplify-server

**Comment by barbaBus** [comment]
I will switch to heplify-server. I need to feed the sip messages to ElasticSearch and use it to build a call leg correlation on an X-header base.

**Comment by lmangani** [comment]
Two options:
- disable `pgsql` entirely in hepop
- use `heplify-server` and configure the ES bulk pusher

Ciao Barbone! ;)

**Comment by xrobau** [comment]
Is this project being abandoned, @lmangani ? Or is the postgresql stuff just not complete?

**Comment by xrobau** [comment]
As I was experiencing the same problem, some quick debugging discovers that the 'sid' field is not being set to a null value set when an OPTIONS packet is being received without a Call-ID header (which is optional, not mandatory).

**Comment by xrobau** [comment]
There is now a pull request to fix this vulnerability.
