### ISSUE TITLE
Missed srcPort/dstPort in the protocol header

### ISSUE THREAD

**Issue by adubovikov** [sipcapture/HEPop#19]
here is the example of an user:

```
{"address":"10.60.139.123","family":"IPv4","port":42726,"time_sec":1581997713868,"time_usec":802,"srcIp":"H_480795380681432","dstIp":"S_5194246480108417"} 
```
- the port should be "srcPort" and or copied to "dstPort". The both fiedls are mandatory!
- the time_sec should be timeSeconds  -Unix timestamp. Now you send it as a Milliseconds. (Javascript Date objecT)
- the time_usec should be timeUseconds  + part of your current time_sec.
- payloadType - missed completely - should be 1000 (Dynamic proto Janus)

```
type ProtocolHeader struct {
	DstIP          string `json:"dstIp"`
	SrcIP          string `json:"srcIp"`
	DstPort        int    `json:"dstPort"`
	SrcPort        int    `json:"srcPort"`
	Protocol       int    `json:"protocol"`
	CaptureID      int    `json:"captureId"`
	CapturePass    string `json:"capturePass"`
	PayloadType    int    `json:"payloadType"`
	TimeSeconds    int    `json:"timeSeconds"`
	TimeUseconds   int    `json:"timeUseconds"`
	ProtocolFamily int    `json:"protocolFamily"`
}
```

the correct syntax:
```
{"address":"10.60.139.123","family":"IPv4","srcPort":42726,"dstPort":42726, "timeSeconds":1581997713,"timeUseconds":868802,"srcIp":"H_480795380681432","dstIp":"S_5194246480108417"} 
```

**Comment by lmangani** [comment]
Done and ready for testing, pending confirmation in #18

**Comment by hangocanh2303** [comment]
@lmangani @adubovikov List call by janus show, but here is another problem. When I clicked session id, it don't show anything and print error. homer-app 1.1.31, UI 7.7.028 prod
![image](https://user-images.githubusercontent.com/19758537/74791523-3483c880-52ed-11ea-91eb-321e679d4efb.png)

![image](https://user-images.githubusercontent.com/19758537/74791556-4feed380-52ed-11ea-9dac-c2ff381cf052.png)

**Comment by adubovikov** [comment]
You probably missed my reply.... We have to release a new homer-app package. Will do during next hours

**Comment by hangocanh2303** [comment]
> You probably missed my reply.... We have to release a new homer-app package. Will do during next hours

ok, thank you very much.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.32
also the packages are in the repository. Please update

**Comment by hangocanh2303** [comment]
> https://github.com/sipcapture/homer-app/releases/tag/1.1.32
> also the packages are in the repository. Please update

unlucky, it still the same result yesterday. 
![image](https://user-images.githubusercontent.com/19758537/74906646-341a2900-53e4-11ea-9bfb-a19a2e9c9de8.png)


And here is dump database 1000_default. 
[dump_1000.zip](https://github.com/sipcapture/HEPop/files/4229142/dump_1000.zip)
You can check it again
![image](https://user-images.githubusercontent.com/19758537/74906693-5449e800-53e4-11ea-94d2-71900a8f58a3.png)

**Comment by adubovikov** [comment]
@lmangani looks like timeUseconds is not correct one:
```
 {"address":"10.60.139.123","family":"IPv4","port":43864,"timeSeconds":1582179343,"timeUseconds":1580597163917807,"srcIp":"H_7122063287949823","dstIp":"S_4703313436377650","srcPort":0,"dstPort":0}
```

should we do srcPort == port ?

**Comment by adubovikov** [comment]
@lmangani and no payloadType

**Comment by adubovikov** [comment]
@hangocanh2303 we have just updated HEPop, can you please pull the latest version and retest it again ?

**Comment by hangocanh2303** [comment]
> @hangocanh2303 we have just updated HEPop, can you please pull the latest version and retest it again ?
I have pull lasest version HEPop and test again after error show, but result the same.

**Comment by adubovikov** [comment]
just now ? We have updated 2 minutes ago!

**Comment by hangocanh2303** [comment]
> just now ? We have updated 2 minutes ago!

![image](https://user-images.githubusercontent.com/19758537/74926002-cbdd3e80-5407-11ea-8bea-4c60b99c0445.png)
newest source but same result

**Comment by adubovikov** [comment]
please send a dump

**Comment by hangocanh2303** [comment]
> please send a dump

[dump_1000.zip](https://github.com/sipcapture/HEPop/files/4230266/dump_1000.zip)
Here is dump file.

**Comment by adubovikov** [comment]
![Screenshot from 2020-02-20 12-50-05](https://user-images.githubusercontent.com/4513061/74931274-90c71500-53df-11ea-89c5-6b6833e229c0.png)
Just uploaded your data and don't see  any issue. Do you use docker ?

**Comment by hangocanh2303** [comment]
> ![Screenshot from 2020-02-20 12-50-05](https://user-images.githubusercontent.com/4513061/74931274-90c71500-53df-11ea-89c5-6b6833e229c0.png)
> Just uploaded your data and don't see any issue. Do you use docker ?

I don't use it.

**Comment by lmangani** [comment]
@hangocanh2303 are you targeting NEW results? The patch is not backwards compatible with existing data having the wrong parameters

**Comment by hangocanh2303** [comment]
> @hangocanh2303 are you targeting NEW results? The patch is not backwards compatible with existing data having the wrong parameters

All data post from janus, and HEPop save to database. I don't understand why "The patch is not backwards compatible with existing data having the wrong parameters"

**Comment by lmangani** [comment]
@hangocanh2303 because it was written with the wrong headers. The patch will only be relevant to traffic captured by HEPop `after` the latest version was applied.

**Comment by hangocanh2303** [comment]
> @hangocanh2303 because it was written with the wrong headers. The patch will only be relevant to traffic captured by HEPop `after` the latest version was applied.

I already installed newest HEPop version, and drop database, and call again. All data is newest

**Comment by adubovikov** [comment]
@hangocanh2303 how did you install homer ? docker or packages ?

**Comment by hangocanh2303** [comment]
> @hangocanh2303 how did you install homer ? docker or packages ?

I installed homer via packages, homer_installer.sh file, not using docker

**Comment by hangocanh2303** [comment]
CentOS Linux release 7.7.1908 (Core)
Homer-app in /usr/local/bin/homer-app
![image](https://user-images.githubusercontent.com/19758537/74939517-98f47400-5422-11ea-8a81-decf6d12ef5d.png)

psql (PostgreSQL) 12.1

**Comment by adubovikov** [comment]
show me your current version

**Comment by hangocanh2303** [comment]
![image](https://user-images.githubusercontent.com/19758537/74949661-a0227e80-5430-11ea-88fe-d843343ebba8.png)
Here is current version homer-app

**Comment by adubovikov** [comment]
so, please do:
```
homer-app -populate-table-db-config -force-populate
```
Go to F12 and remove everything:

Under Application -> Local Storage.
Under Application -> Session Storage.

Clean Javascript cache

and test again.

**Comment by hangocanh2303** [comment]
> so, please do:
> 
> ```
> homer-app -populate-table-db-config -force-populate
> ```
> 
> Go to F12 and remove everything:
> 
> Under Application -> Local Storage.
> Under Application -> Session Storage.
> 
> Clean Javascript cache
> 
> and test again.

ok, @adubovikov , I will report result here tommorrow, now I can't connect to server because session terminated.

**Comment by adubovikov** [comment]
the mapping is correct now. Keep track in the original ticket
