### ISSUE TITLE
Weird metrics in influxdb

### ISSUE THREAD

**Issue by aberrios85** [sipcapture/HEPop#21]
So hepop processes a Janus report with a log line like so:

```
hepop                                | [04:29:55 PM] ✔ JANUS REPORT [{"emitter":"SFU","event":{"base":48000,"bytes-received":3719876,"bytes-received-lastsec":4270,"bytes-sent":5538470,"bytes-sent-lastsec":7260,"in-link-quality":100,"in-media-link-quality":100,"jitter-local":3,"jitter-remote":6,"lost":0,"lost-by-remote":4,"media":"audio","nacks-received":0,"nacks-sent":0,"out-link-quality":100,"out-media-link-quality":100,"packets-received":41505,"packets-sent":41385,"retransmissions-received":0,"rtt":27},"handle_id":2321235889037909,"opaque_id":"6152-XXXX","session_id":8115630803420514,"timestamp":1583512195570972,"type":32}]
```

but Influxdb has stats like so:

```
time                 bytes-received bytes-sent handle           in-link-quality in-media-link-quality jitter-local jitter-remote lost lost-by-remote medium nacks-received nacks-sent opaque_id     out-link-quality out-media-link-quality packets-received packets-sent rtt session          type
----                 -------------- ---------- ------           --------------- --------------------- ------------ ------------- ---- -----
--------- ------ -------------- ---------- ---------     ---------------- ---------------------- ---------------- ------------ --- -------          ----
2020-03-06T16:29:30Z 186472819      277602382  2321235889037909 6500            6500                  181          241           0    150            audio  0              0          6152-XXXX     6500             6500                   2072876          2072876      1868 8115630803420514 32
```

Why are the metrics totally  off? Am I being a complete influxdb noob?

**Comment by aberrios85** [comment]
Ah okay, I changed `"period": 30000` to`"period": 1000`  in the hepop settings under metrics: influx and that seems to have fixed it.

I take it hepop is batching up type 32 events from janus and for some reason summing the values before inserting them? Is that correct?

Is there a way to stop hepop summing the values?

I'm also getting a lot of inserts into influxdb where the metric values are 0. I'm just looking through the hepop source and my debug logs now to understand why.

**Comment by lmangani** [comment]
Hi @aberrios85 I suggest you take a look at the code - All messages are stored as-is with the exception of type 32 which are discarded and converted to native timeseries w/ tags aggregated by the pediod of choice to reduce the backend complexity when desirable - also in most cases, those stats only really make sense in groups and not individually. 

This all being said, this has to work for USERS so feel free to report your experience or any change request idea. Let me know if you have any further questions and thanks for testing HEPop!
