### ISSUE TITLE
HEPop dosen't receive events from JANUS

### ISSUE THREAD

**Issue by NinoFares** [sipcapture/HEPop#23]
Hi guys,

I try to capture Janus Events with HEPop with http config, but HEPop dosen't receive events.

my config Janus Events Handler : 
general :
{
  enabled = "yes";
  events = "sessions, handles, stats_sum, plugins, core";
  grouping = "yes";
  backend = "http://JanusIP:8097";
};
my config Hepop:
{
  "id" : "HEPop101",
  "socket": "http",
  "port": 8097,
  "address": "JanusIP",
  "queue": {
    "timeout": 2000,
    "maxSize": 1000,
    "useInterval": true
  },
  "dbName": "homer_data",
  "tableName": "hep_proto_1_default",
  "db": {
        "debug": true,
        "pgsql":{
          "host": "127.0.0.1",
          "port": 5432,
          "user": "homer",
          "password": "homer_password",
          "database": "homer_data"
        }
  },
  "metrics": {
        "influx":{
                "period": 30000,
                "dbName": "hep",
                "hostname": "localhost:9999"
        }
  },
  "debug": true
}
I used Hepipe.JS to test the capture of these events, and it's work, but not with HEPop.

Thanks for your help !

**Comment by lmangani** [comment]
If active, try disabling bulk events in Janus to confirm if this is the issue.

**Comment by lmangani** [comment]
Just to be specific - when you say it does not receive, does it means you do not see the packets arriving at the interface, or you do not see them handled by HEPop?

**Comment by NinoFares** [comment]
How i disable bulk events ?
And both, i dont see them arriving to the interface thus Hepop does not handle them.

**Comment by lmangani** [comment]
How have you configured Janus to send them is the starting point.

**Comment by lmangani** [comment]
You should have something similar to this in your `janus.eventhandler.sampleevh.jcfg`
```
general: {
	enabled = true	
	events = "all"		
	grouping = false		
	json = "indented"	
	backend = "http://hepop:8080"
}
```

**Comment by NinoFares** [comment]
I thought Hepop was going to get them from http://JANUSIP:8097 directly, i will try that :D
So what shoud i keep this part of Hepop config like that ?
{
"id" : "HEPop101",
"socket": "http",
"port": 8097,
"address": "JanusIP",
"queue": {
"timeout": 2000,
"maxSize": 1000,
"useInterval": true
},

**Comment by lmangani** [comment]
`HEPop` is a server with a socket Janus can send events to. That's really it.

### Janus (sends events)
```
general: {
	enabled = true	
	events = "all"		
	grouping = false		
	json = "indented"	
	backend = "http://hepop:8080"
}
``` 
### HEPop (receives events)
```
{
  "id" : "HEPop101",
  "socket": "http",
  "port": 8080,
  "address": "0.0.0.0",
  ...
}
```

**Comment by NinoFares** [comment]
It works :D ! Thank you so much !
