### ISSUE TITLE
Metrics with prometheus instead of influx 

### ISSUE THREAD

**Issue by NinoFares** [sipcapture/HEPop#27]
Hi guys,

I'd like to set up a hepop configuration with prometheus instead of influx for the metrics and I couldn't find that on your configuration examples.
Can you explain me how to do it? and an example of configuration?

Thanks !

**Comment by lmangani** [comment]
HI @NinoFares 
The prometheus exporter is not implemented but its fully supported by `crow` so it should take a few [lines only](https://github.com/robey/crow-metrics/blob/master/docs/manual.md#exportprometheus). The hooking point is here if you want to try: https://github.com/sipcapture/HEPop/blob/master/src/metrics.js#L8

**Comment by NinoFares** [comment]
OK! I'll try to do that, thanks for your answer @lmangani !
