### ISSUE TITLE
Request: docker image tags that map to code version

### ISSUE THREAD

**Issue by jeff-knurek** [sipcapture/HEPop#30]
[experienced]
at the moment, the docker image tags available consist of a few older builds and **latest**
https://hub.docker.com/r/sipcapture/hepop/tags

[Desired state]
It would be great if there were versioned tags in docker hub. 

Right now it seems that the only code versioning is based on a value in the package.json file. 
That value could possibly be used by CI tool https://gist.github.com/DarrenN/8c6a5b969481725a4413, but maybe it's better to introduce git tags, or maybe the easiest would be to use the git sha as the docker tag.

**Comment by lmangani** [comment]
Hi @jeff-knurek thanks for this improvement proposal. That's indeed correct, we only build latest on master and do not keep other tags. Most users relying on this deploy their own builds so there was no need for any archive of past versions. We used to build with codefresh but since they updated, all recipes need attention. Would be happy to implement any suggestions to make this as community friendly and transparent as possible.

**Comment by jeff-knurek** [comment]
I've started using Github Actions in my open source projects, and it seems to provide simple CI with great transparency. :man_shrugging: 

Here's a pretty basic `on push` flow that checks out code and runs a few npm commands: https://docs.github.com/en/actions/guides/building-and-testing-nodejs#starting-with-the-nodejs-workflow-template

and one for publishing images to docker hub: https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-docker-hub

----
if you share the old codefresh pipeline, I can try to port the same into github Actions in a PR for review. It'd require setting up docker auth on your end: 
> username and password: This is your Docker Hub username and password. We recommend storing your Docker Hub username and password as encrypted secrets in the your GitHub repository so they aren't exposed in your workflow file. For more information, see "Creating and using encrypted secrets."

**Comment by lmangani** [comment]
@jeff-knurek invited you as maintainer to this repository in case you want to help us with that

**Comment by jeff-knurek** [comment]
closing as work was done in #31
