### ISSUE TITLE
Streaming Janus events to Loki

### ISSUE THREAD

**Issue by geo-matheou** [sipcapture/HEPop#41]
Hello, 

I am using the following configuration to stream janus events to loki:
`{
  "id" : "HEPOP_ID",
  "socket": "http",
  "port": 8090,
  "address": "0.0.0.0",
  "queue": {
    "timeout": 2000,
    "maxSize": 1000,
    "useInterval": true
  },
  "db": {
	"loki" : {
		"url": "http://xxx:3100/api/prom/push"
	}
  },
  "debug": true
}`

The labels that are created for loki are the following:  "labels":"{type=\"json\", id=\"undefined\"}"
How can I set a proper value for id? 
Also, how can I extend the labels array with more fields? 

Thank you in advance,
George

**Comment by lmangani** [comment]
Hello @geo-matheou you don't really need HEPop for this - and sadly HEPop is no longer actively maintained.

But no problem! Check out this [paStash](https://github.com/sipcapture/paStash/wiki/Example%3A-Janus-Events) recipe for Janus which should be more flexible for your use-case allowing your to fine-tune the events and tags more granularly.

The above is designed for our project [cLoki](https://cloki.org) which implements a full LogQL API over clickhouse, but should work just as good with Grafana Loki. Feel free to give it a try if you'd like to access your events in multiple ways past the LogQL API through ClickHouse.

**Comment by geo-matheou** [comment]
Thank you very much @lmangani. I will try it and post any feedback if necessary.
