### ISSUE TITLE
Give Loki some love

### ISSUE THREAD

**Issue by negbie** [sipcapture/HEPop#8]
Have fun:

https://github.com/grafana/loki/commit/da27baad2ce4fe65569c8d298a92070af287a14d

**Comment by negbie** [comment]
https://github.com/grafana/loki/blob/master/docs/api.md

**Comment by lmangani** [comment]
Baseline implemented with https://github.com/sipcapture/HEPop/commit/5684f35cc4a35d0cd1095b5505ff3f1dc1966d9f
